### ISSUE TITLE
Installation and use of Autoprognosis

### ISSUE THREAD

**Issue by bbb801** [ahmedmalaa/AutoPrognosis#1]
Dear  ahmedmalaa,

Thanks for your sharing.
I have two questions when begining using your code,
1. As to installation, is it necessary to intall the tool in Linux anaconda, or can I use it in Windows with Anaconda and then use it under Windows system?
2. When I open 'AutoPrognosis API Tutorial' (AutoPrognosis/alg/autoprognosis/tutorial_autoprognosis_api.ipynb), it stops at 'import initpath_ap'' and 'import utilmlab'. I found "ModuleNotFoundError: No module named 'initpath_ap' first". 
Could you give some suggestions?

**Comment by athomsvphd** [comment]
Hi @bbb801 , Has this been resolved? I'm facing the same error.

**Comment by athomsvphd** [comment]
Hi @bbb801 @ahmedmalaa , has this error been resolved? I'm facing the same error. Any help would be much appreciated.
