### ISSUE TITLE
'Interpreter' module

### ISSUE THREAD

**Issue by bbb801** [ahmedmalaa/AutoPrognosis#2]
Dear Sir or Madam,

Could your tell how to use the 'Interpreter' module mentioned in the paper, AutoPrognosis: Automated Clinical Prognostic Modeling via Bayesian Optimization with Structured Kernel Learning?

Regards,
Beato

**Comment by ahmedmalaa** [comment]
Hi Beato,

This feature is not yet added to the current release. We will add an improved interpreter including different types of interpretations (feature importance, post-hoc instance-wise feature importance, symbolic modeling, etc) in the next release.

Thank you!
