### ISSUE TITLE
Error with Installation of AutoPrognosis

### ISSUE THREAD

**Issue by athomsvphd** [ahmedmalaa/AutoPrognosis#3]
Hi, I'm trying to install AutoPrognosis in my CentOS7 system. I have installed all the dependencies for AutoPrognosis in the requirements.txt and have followed the installation instructions. However, I get importing errors with initpath_ap, utilmlab. It seems no module is found for the same. Any thoughts? Many thanks in advance. Cheers!

**Comment by ahmedmalaa** [comment]
Hi Angelina, can you please provide more details on the error you are encountering? The files you mentioned are in the init and util folders.

Thanks

**Comment by athomsvphd** [comment]
Hi Ahmed, Many thanks for your message. I was able to sort this from the init and util forlders. Was wondering about the feature selection part. Is there a scoring function for each feature used for the final ensembl model that is being built? similar to 'table 3: Variable ranking by their contribution to the predictions of AutoPrognosis' from paper at plos one- 'Cardiovascular disease risk prediction using automated machine learning: A prospective study of 423,604 UK Biobank participants.' 
Many thanks in advance.

**Comment by ahmedmalaa** [comment]
Hi Angelina. Unfortunately, the model interpretability modules (including feature scoring) are not yet incorporated into this release. You can alternatively use any post-hoc algorithms for feature selection and ranking, or evaluate feature importance by dropping one feature at a time and computing the model accuracy. Thanks,

**Comment by athomsvphd** [comment]
Hey Ahmed! Thanks for the suggestion. Your work at the plos one paper was really awesome! Do give me a shout when the interpretability module is out, hopefully anytime soon? Cheers!

**Comment by ahmedmalaa** [comment]
Sure, will do. Thanks.
