### ISSUE TITLE
ModuleNotFoundError: No module named 'initpath_ap'

### ISSUE THREAD

**Issue by PETEGOTHEAT** [ahmedmalaa/AutoPrognosis#4]
Hello ahmedmalaa,

Thank you for putting this together. 

I saw this same issue posted on July 3, but I do not see the resolution posted: https://github.com/ahmedmalaa/AutoPrognosis/issues/1

After installing on Windows and following the 'AutoPrognosis API Tutorial' I receive the error: ModuleNotFoundError: No module named 'initpath_ap'

Do you have any suggestions?

**Comment by ahmedmalaa** [comment]
Hi PETEGOTHEAT,

initpath_ap is inside AutoPrognosis/alg/autoprognosis/. Are you sure you're running the API tutorial from the correct directory?
